# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 15:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('aldryn_newsblog', '0016_auto_20180329_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletranslation',
            name='og_description',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='OG Description'),
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='og_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article_image_og', to=settings.FILER_IMAGE_MODEL, verbose_name='OG Image'),
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='og_title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='OG Title'),
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='twitter_description',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='Twitter Description'),
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='twitter_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article_image_twitter', to=settings.FILER_IMAGE_MODEL, verbose_name='Twitter Image'),
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='twitter_title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Twitter Title'),
        ),
    ]
